# Generated by Django 5.2.5 on 2025-09-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_attendee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('attendee', 'Attendee')], default='attendee', max_length=20),
        ),
    ]
