# Generated by Django 5.2.5 on 2025-09-04 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_category_session_speaker_tickettype_and_more'),
        ('registrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='events.tickettype'),
        ),
    ]
